config/routes.rb
Neighborhoods::Application.routes.draw do
 
  resources :places
  resources :photos
  resources :posts
  resources :places
  resources :friendships, only: [:create, :destroy]

  devise_for :users

  root :to => redirect('/users/sign_up')

  authenticated :user do
    root to: "users#main_feed"
  end
 
  match "users/:id/add_neighborhood/:neighborhood_id" => "users#add_neighborhood", :via => :post 
  match "users/:id/main_feed"                         => "users#main_feed"
  
  resources :users do
    resources :posts
    resources :friendships, only: [:index]
  end

  match "neighborhoods/find"                                => "neighborhoods#find"
  match "neighborhoods/:id/preview"                         => "neighborhoods#preview"
  match "neighborhoods/:id/join"                            => "neighborhoods#join",          as: :join_neighborhood
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave",         as: :leave_neighborhood, via: :post
  match "neighborhoods/:id/primary"                         => "neighborhoods#primary",       as: :primary_neighborhood, via: :post
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave"
  match "neighborhoods/:id/select_photos"                   => "neighborhoods#select_photos"
  match "neighborhoods/:id/add_photos"                      => "neighborhoods#add_photos",    :via => :post
  match "neighborhoods/:id/add_to_favorites"                => "favorites#add_to_favorites",  :via => :post
  
  resources :neighborhoods do
    resources :posts
    resources :places do
      resources :posts
    end
  end
  
  match "neighborhoods/:neighborhood_id/places/:id/add_to_favorites" => "favorites#add_to_favorites", :via => :post
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :gender, :birthday, :about

  validates_presence_of :first_name, :last_name, :gender, :birthday

  has_many :neighborhood_users
  has_many :neighborhoods, through: :neighborhood_users

  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :places
  has_many :favorites, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :ownerships, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end

  def profile_picture(size = :small)
    if self.profile_picture_id != nil 
      photo = Photo.find(self.profile_picture_id)
      photo.image.url(size)
    else
      "missing_profile_picture.png"
    end
  end

  def primary_neighborhood
    neighborhood_users.where(primary: true).first.neighborhood
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :has_neighborhood?, only: :main_feed
  before_filter :allow_if_current_user, only: [:main_feed, :edit, :update]

  def add_neighborhood
    neighborhood = Neighborhood.find(params[:neighborhood_id])
    if current_user.neighborhoods.include?(neighborhood)
      flash[:notice] = "You already belong to this neighborhood"
    else
      primary = current_user.neighborhoods.empty?
      NeighborhoodUser.create(user_id: current_user.id, neighborhood_id: neighborhood.id, primary: primary)
      flash[:success] = "You've successfully joined this neighborhood"
    end
    redirect_to root_path
  end

  def main_feed
    user_posts = current_user.posts
    friends_posts = Post.where(user_id: current_user.friends)
    neighborhood_posts = Post.where(user_id: current_user.friends, neighborhood_id: current_user.neighborhoods)
    @posts = (user_posts + friends_posts + neighborhood_posts).sort_by(&:id).reverse

    if current_user.friends.empty?
      @suggested_friends = User.where("id != ?", current_user.id).limit(5)
    else  
      @suggested_friends = User.where("id not in (?) AND id != ?", current_user.friends, current_user.id).limit(5)
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(neighborhood_id: nil).order 'created_at DESC'
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      if params[:image].present?
        photo = Photo.new(image: params[:image], user_id: @user.id) 
        photo.save
        @user.profile_picture_id = photo.id
        @user.save
      end    
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      flash[:error] = "Unable to update your profile"
      render action: "edit" 
    end
  end

  private

  def allow_if_current_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end

  def has_neighborhood?
    if current_user.neighborhoods.empty?
      redirect_to '/neighborhoods/find'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_nav_link(user, user_id)
    current_user = find_user(user, user_id)
    link_to current_user.full_name, current_user, class: 'profile-name'
  end

  def find_user(user, user_id)
    if user_id.present?
      user.id == user_id ? user : User.find(user_id)
    else
      user
    end
  end
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9">
          <%= form_for @user, :html => { :multipart => true } do |f| %>
          <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name, placeholder: "First Name" %>
          </div>
          <div> 
          <%= f.label :last_name %>
          <%= f.text_field :last_name, placeholder: "Last Name" %>
          </div>  
          <div> 
          <%= f.label :about %>
          <%= f.text_area :about, placeholder: "Say something about yourself", rows: 3 %>
          </div>  
          <div>
            <%= f.radio_button :gender, "male" %>
            <%= f.label :gender_male, "Male" %>
         
            <%= f.radio_button :gender, "female" %>
            <%= f.label :gender_female, "Female" %>
          </div>
         
          <div>
            <%= f.label :birthday %>
            <%= f.date_select :birthday, order: [:month, :day, :year] %>
          </div>  
          <div>
            <span>Profile Picture: </span><%= file_field_tag 'image' %></div>
          <div><%= f.submit "Update Profile" %></div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_header.html.erb
<div class="inner bottom-border">
  <div class="container">
    <div class="row">
      <div class="span6">
        <ul class="nav nav-tabs">
          <li class= <%= 'active' if tab_active?(:users) %>>
            <%= user_nav_link(current_user, (params[:id] || params[:user_id])) %>
          </li>
          <li><a href="javascript:void(0)">About</a></li>
          <li><a href="javascript:void(0)">Photos</a></li>
          <li class= <%= 'active' if tab_active?(:friendships) %>>
            <%= link_to "Friends", user_friendships_path(@user) %>
          </li>
          <li><a href="javascript:void(0)">Favorites</a></li>
        </ul>
      </div>
      <div class="main-actions span3">
        <%= link_to "edit profile", edit_user_path(@user) if @user == current_user %>
        <%= link_to("Add Friend", friendships_path(friend_id: @user), method: :post) unless (@user == current_user or already_friends?(@user)) %>
        <a href="#"><i class="icon-search single"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "header" %>
<%= render "form" %>

app/views/users/main_feed.html.erb
<div class="container">
    <div class="row">
      <div id="cover-fix"></div>
      <section id="main-feed" class="span9">
        <div class="row">
          <div id="identity-share" class="span9">
            <div class="row">
              <div class="identity span3">
                <div class="inner-margin2">
                  <div class="inner-padding8">
                    <%= link_to(image_tag(@user.profile_picture(:small), class: "med-thumbnail"), @user) %>
                    <div class="profile-ident">
                      <%= link_to current_user.full_name, current_user, class: "profile-name" %>
                      <br />
                      <span><%= link_to "edit profile", edit_user_path(@user) if @user == current_user %></span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="share offset3 span6">
                <div class="inner-margin2">
                  <div class="inner-padding8">
                    <div id="share-controls">
                      <a href="#"><i class="icon-camera"></i></a><a href="#"><i class="icon-link"></i></a><a href="#"><i class="icon-lock fright"></i></a>
                    </div>
                    <%= form_tag('/posts/') do %>
                      <input id="post_temp_field" name="post[content]" placeholder="Go ahead, share something!" size="30" type="text">
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="sidebar-left" class="span3">
            <div class="block">
              <h5>
                Jump to a neighborhood...
              </h5>
              <ul>
              <% @user.neighborhoods.each do |neighborhood| %>
                <li>
                  <a href="<%= neighborhood_path(neighborhood) %>">
                    <div class="neighborhood-notifications">3</div>
                    <%= neighborhood.name %>
                    <%= '(primary)' if is_primary?(neighborhood) %>
                  </a>
                </li>
              <% end %>
              </ul>
              <a href="/neighborhoods/find" class="white-btn"><i class="icon-circle-arrow-right"></i>Join Another Neightborhood</a>
            </div>
            <div class="block manage">
              <h5>Manage...</h5>
              <ul>
              <li><a href="#"><i class="icon-heart"></i>My Favorites</a></li>
              <li>
                <a href="#"><i class="icon-map-marker"></i>My Places</a>
                <a href="#" class="add"><i class="icon-plus"></i></a>
              </li>
              <li>
                <a href="#"><i class="icon-picture"></i>My Photos</a>
                <a href="#" class="add"><i class="icon-plus"></i></a>
              </li>
              <li>
                <a href="#"><i class="icon-calendar"></i>My Events</a>
                <a href="#" class="add"><i class="icon-plus"></i></a>
              </li>
              </ul>
            </div>
          </div>
          <div class="span6">
            <hr>
            <div id="neighborhood-feed-filter"><div>Neighborhood Feed <i class="icon-caret-down"></i></div></div>
            <% @posts.each do |post| %>
              <%= render partial: 'posts/post', locals: { post: post } %>
            <% end %>
          </div>
        </div>
      </section>
      <section id="sidebar-right" class="span3">
        <h5>Suggested Friends</h5>
        <ul>
        <% @suggested_friends.each do |person| %>
          <li>
            <%= link_to(image_tag(person.profile_picture(:small), class: "small-thumbnail"), person) %>
            <div class="profile-ident">
              <%= link_to person.full_name, person, class: "profile-name" %>
              <br />
              <p>
                <% neighborhood = person.primary_neighborhood %>
                <%= link_to person.primary_neighborhood.try(:name), neighborhood_path(person.primary_neighborhood) %>
              </p>
            </div>
            <%= link_to "Add", friendships_path(friend_id: person), method: :post, class: "white-btn" %>
          </li>
        <% end %>
        </ul>
      </section>
    </div>
</div>

app/views/users/show.html.erb
<%= render "header" %>
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <section class="span9">
          <div class="share">
            <div class="inner-margin2">
              <div class="inner-padding8">
                <div id="share-controls">
                  <a href="#"><i class="icon-camera"></i></a><a href="#"><i class="icon-link"></i><a href="#"><i class="icon-lock fright"></i></a>
                </div>
                <%= form_tag('/posts/') do %>
                  <input id="post_temp_field" name="post[content]" placeholder="Go ahead, share something!" size="30" type="text">
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="span9">
            <% @posts.each do |post| %>
              <%= render partial: 'posts/post', locals: { post: post } %>
            <% end %>
            </div>
          </div>
        </section>
        <section id="profile-sidebar" class="span3">
          <%= link_to(image_tag(@user.profile_picture(:small), class: "large-thumbnail"), @user, class: "ppic") %>
          <ul>
          <!-- probably should move this to another section -->
          <% @user.neighborhoods.each do |nh| %>
            <li>
              <a href="<%= neighborhood_path(nh) %>"><i class="icon-arrow-right"></i><%= nh.name %></a>
            </li>
          <% end %>
          </ul>
          <p>
            <%= @user.about %> <!-- will print user about information if it exists -->
          </p>
        </section>
        
      </div>
    </div>
  </div>
</div>