config/routes.rb
Neighborhoods::Application.routes.draw do
 
  resources :places
  resources :photos
  resources :posts
  resources :places
  resources :friendships, only: [:create, :destroy]

  devise_for :users

  root :to => redirect('/users/sign_up')

  authenticated :user do
    root to: "users#main_feed"
  end
 
  match "users/:id/add_neighborhood/:neighborhood_id" => "users#add_neighborhood", :via => :post 
  match "users/:id/main_feed"                         => "users#main_feed"
  
  resources :users do
    resources :posts
    resources :friendships, only: [:index]
  end

  match "neighborhoods/find"                                => "neighborhoods#find"
  match "neighborhoods/:id/preview"                         => "neighborhoods#preview"
  match "neighborhoods/:id/join"                            => "neighborhoods#join",          as: :join_neighborhood
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave",         as: :leave_neighborhood, via: :post
  match "neighborhoods/:id/primary"                         => "neighborhoods#primary",       as: :primary_neighborhood, via: :post
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave"
  match "neighborhoods/:id/select_photos"                   => "neighborhoods#select_photos"
  match "neighborhoods/:id/add_photos"                      => "neighborhoods#add_photos",    :via => :post
  match "neighborhoods/:id/add_to_favorites"                => "favorites#add_to_favorites",  :via => :post
  
  resources :neighborhoods do
    resources :posts
    resources :places do
      resources :posts
    end
  end
  
  match "neighborhoods/:neighborhood_id/places/:id/add_to_favorites" => "favorites#add_to_favorites", :via => :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id, :neighborhood_id, :place_id

  belongs_to :user
  belongs_to :neighborhood
  belongs_to :place

  validates_presence_of :user_id, :content
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
 
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    set_vars_based_on_params
  end

  def edit
    @post = Post.find(params[:id])
    set_vars_based_on_params
  end

  def create
    post = Post.new(params[:post].merge(user_id: current_user.id))
    post.save! 
    redirect_to request.env['HTTP_REFERER']
  end

  def update
    @post = Post.find(params[:id])
    set_vars_based_on_params

    if @post.update_attributes(params[:post])
      redirect_by_post_type
    else
      defined?(@neighborhood) ? redirect_to(edit_neighborhood_post_path(@neighborhood, @post)) : render(action: "edit")
    end
  end

  def destroy
    Post.destroy params[:id]
    redirect_to request.env['HTTP_REFERER']
  end

  private

  def set_vars_based_on_params
    @neighborhood = Neighborhood.find(params[:neighborhood_id]) unless params[:neighborhood_id].nil?
    @place = Place.find(params[:place_id]) unless params[:place_id].nil?

    if defined?(@place) and defined?(@neighborhood)
      @submit_post_url = neighborhood_place_post_path(@neighborhood, @place, @post)
    elsif defined?(@neighborhood)
      @submit_post_url = neighborhood_post_path(@neighborhood, @post)
    else
      @submit_post_url = post_path(@post)
    end
  end

  def redirect_by_post_type
    if defined?(@place) and defined?(@neighborhood)
      redirect_to neighborhood_place_path(@neighborhood, @place)
    elsif defined?(@neighborhood)
      redirect_to @neighborhood
    else
      redirect_to @post
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_edit_path(post)
    puts "+++++++++++++++++++++++++++++++"
    if defined?(@place) and defined?(@neighborhood)
      edit_neighborhood_place_post_path(@neighborhood, @place, post)
    elsif defined?(@neighborhood)
      edit_neighborhood_post_path(@neighborhood, post)
    else
      edit_post_path(post)
    end
  end

  def get_delete_path(post)
    if defined?(@place) and defined?(@neighborhood)
      neighborhood_place_post_path(@neighborhood, @place, post)
    elsif defined?(@neighborhood)
      neighborhood_post_path(@neighborhood, post)
    else
      post_path(post)
    end
  end
end

app/views/posts/_form.html.erb
<div class="share">
   <div class="inner-margin2">
     <div class="inner-padding8">
       <div id="share-controls">
         <a href="#"><i class="icon-camera"></i></a><a href="#"><i class="icon-link"></i><a href="#"><i class="icon-lock fright"></i></a>
       </div>
       <%= form_for @post, url: @submit_post_url do |f| %>
         <% if @post.errors.any? %>
           <div id="error_explanation">
             <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
       
             <ul>
             <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
             </ul>
           </div>
         <% end %>
       
         <div class="actions">
           <%= f.hidden_field :user_id, :value => current_user.id %>
           <%= f.hidden_field(:neighborhood_id, :value =>  @neighborhood.id) if defined? @neighborhood %>
           <%= f.hidden_field(:place_id, :value =>  @place.id) if defined? @place %>
           <%= f.text_field :content, placeholder: "Go ahead, share something!" %>
         </div>
       <% end %>

     </div>
   </div>
 </div>

app/views/posts/_mini_post.html.erb
<p><%= link_to mini_post.user.full_name, mini_post.user %> from <%= link_to mini_post.neighborhood.name, mini_post.neighborhood %></p>
<p><%= mini_post.content %></p>

app/views/posts/_post.html.erb
<article class="post">
  <div class="inner-margin2">
    <div class="inner-padding8">
      <% if post.user_id == current_user.id %>
        <div class="btn-group post-options">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-caret-down"></i>
          </a>
          <ul class="dropdown-menu pull-right">
            <li><%= link_to "edit", get_edit_path(post) %></li>
            <li><%= link_to 'delete', get_delete_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </div>
      <% end %>
      <%= link_to(image_tag(post.user.profile_picture, class: "med-thumbnail"), post.user) %>
      <div class="profile-ident">
        <%= link_to(post.user.full_name, post.user, class: "profile-name") %>
        <br />
        <p>
        <span class="date">
          <%=  post.created_at.strftime("%l:%M %p %m/%d/%y") %>
        </span>
        <span class="date">
          <% neighborhood = current_user.primary_neighborhood %>
          <%= link_to neighborhood.name, neighborhood_path(neighborhood) if neighborhood %>
        </span>
        </p>
      </div>
      <p><%= post.content %><p>
    </div>
    <div class="post-actions">
      <a href="#"><i class="icon-thumbs-up"></i></a>
    </div>
  </div>
  <div id="arrow-up">
    <div id="arrow-container">
      <div class="arrow-up backdrop"></div>
      <div class="arrow-up inner-white"></div>
      <div class="arrow-up inner-color"></div>
    </div>
  </div>
  <div class="post-comments">
    <div class="inner-margin2">
      <div class="inner-padding8">
        <input placeholder="Add a comment..." type="text">
      </div>
    </div>
  </div>
</article>

app/views/posts/edit.html.erb
  <%= render 'neighborhoods/header' %>
  <%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% if defined? @neighborhood %>
  <%= render 'new_neighborhood_post' %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>