config/routes.rb
Neighborhoods::Application.routes.draw do
 
  resources :places
  resources :photos
  resources :posts
  resources :places
  resources :friendships, only: [:create, :destroy]

  devise_for :users

  root :to => redirect('/users/sign_up')

  authenticated :user do
    root to: "users#main_feed"
  end
 
  match "users/:id/add_neighborhood/:neighborhood_id" => "users#add_neighborhood", :via => :post 
  match "users/:id/main_feed"                         => "users#main_feed"
  
  resources :users do
    resources :posts
    resources :friendships, only: [:index]
  end

  match "neighborhoods/find"                                => "neighborhoods#find"
  match "neighborhoods/:id/preview"                         => "neighborhoods#preview"
  match "neighborhoods/:id/join"                            => "neighborhoods#join",          as: :join_neighborhood
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave",         as: :leave_neighborhood, via: :post
  match "neighborhoods/:id/primary"                         => "neighborhoods#primary",       as: :primary_neighborhood, via: :post
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave"
  match "neighborhoods/:id/select_photos"                   => "neighborhoods#select_photos"
  match "neighborhoods/:id/add_photos"                      => "neighborhoods#add_photos",    :via => :post
  match "neighborhoods/:id/add_to_favorites"                => "favorites#add_to_favorites",  :via => :post
  
  resources :neighborhoods do
    resources :posts
    resources :places do
      resources :posts
    end
  end
  
  match "neighborhoods/:neighborhood_id/places/:id/add_to_favorites" => "favorites#add_to_favorites", :via => :post
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  attr_accessible :name, :city_id, :description
  
  has_many :neighborhood_users
  has_many :users, through: :neighborhood_users

  belongs_to :city
  has_many :posts, dependent: :destroy
  has_many :photos
  has_many :places
  has_many :favorites, dependent: :destroy
  has_many :ownerships, dependent: :destroy
  has_many :owners, through: :ownerships
  
  validates_presence_of   :name
  validates_uniqueness_of :name, :scope => :city_id
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  include OwnershipsHelper
  before_filter :authenticate_user!
  before_filter :allow_if_owner, only: [:edit, :update, :destroy]
  
  def find
    @user = current_user
    @states = State.order :name
  end

  def join
    neighborhood = Neighborhood.find params[:id]
    primary = current_user.neighborhoods.empty?
    NeighborhoodUser.create(user_id: current_user.id, neighborhood_id: neighborhood.id, primary: primary)
    flash[:success] = "You've successfully joined this neighborhood"
    redirect_to neighborhood
  end

  def leave
    nh = NeighborhoodUser.where(user_id: current_user.id, neighborhood_id: params[:id]).first
    if nh.primary?
      flash[:error] = 'Please set a new neighborhood as primary before leaving this one'
    else
      nh.destroy
      flash[:success] = "You've left the neighborhood. You'll be missed"
    end
    redirect_to root_path
  end

  def primary
    old_primary = current_user.neighborhood_users.where(primary: true).first
    old_primary.update_attributes(primary: false)
    new_primary = NeighborhoodUser.where(user_id: current_user.id, neighborhood_id: params[:id]).first
    new_primary.update_attributes(primary: true)
    flash[:success] = "You've changed your primary neighborhood"
    redirect_to new_primary.neighborhood
  end

  def index
    if params[:city_id]
      @neighborhoods = Neighborhood.where("city_id = ?", params[:city_id]).order(:name) 
    else
      @neighborhoods = Neighborhood.order(:name)
    end
    respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
  end

  def manage
    @neighborhoods = current_user.neighborhood_users
  end

  def preview
    @neighborhood = Neighborhood.find params[:id]
  end

  def new
    @neighborhood = Neighborhood.new
    @city = City.find(params[:city_id])
  end

  def create
    @neighborhood = Neighborhood.new(params[:neighborhood])
    if @neighborhood.save
      primary = current_user.neighborhoods.empty?
      NeighborhoodUser.create(user_id: current_user.id, neighborhood_id: @neighborhood.id, primary: primary)
      photo = Photo.new(image: params[:image], user_id: current_user.id, neighborhood_id: @neighborhood.id)
      photo.save
      ownership = current_user.ownerships.build(neighborhood_id: @neighborhood.id).save
      flash[:success] = "Neighborhod successfully created"
      redirect_to @neighborhood
    elsif @neighborhood.errors.messages.values.include?(["can't be blank"])
      redirect_to :action => "find"
    elsif @neighborhood.errors.messages.values.include?(["has already been taken"])
      flash[:notice] = "It looks like this neighborhood already exists."
      @neighborhood = Neighborhood.where("name  = ? AND city_id = ?", params[:neighborhood][:name], params[:neighborhood][:city_id]).first
      redirect_to @neighborhood
    end
  end
  
  def show
    @neighborhood = Neighborhood.find(params[:id])
    @posts = @neighborhood.posts.order("created_at DESC")
    @post = Post.new
    @submit_post_url = neighborhood_posts_path(@neighborhood)
    @places = @neighborhood.places
  end

  def select_photos
    @neighborhood = Neighborhood.find(params[:id])
    @photo = Photo.new
    @submit_url = "/neighborhoods/#{@neighborhood.id}/add_photos"
  end

  def add_photos
    @neighborhood = Neighborhood.find(params[:id])
    @photo = Photo.new(params[:photo])
    @photo.save
    @neighborhood.photos << @photo
    redirect_to @neighborhood 
  end

  def edit
    @neighborhood = Neighborhood.find params[:id]
  end

  def update
    @neighborhood = Neighborhood.find params[:id]
    if @neighborhood.update_attributes params[:neighborhood]
      if params[:image].present?
        Photo.create(image: params[:image], user_id: current_user.id, neighborhood_id: @neighborhood.id)
      end
      flash[:success] = "Neighborhod successfully updated"
      redirect_to @neighborhood
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def allow_if_owner
    @neighborhood = Neighborhood.find(params[:id])
    redirect_to root_path unless is_owner?(@neighborhood)
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
  def is_primary?(neighborhood)
    current_user.primary_neighborhood == neighborhood
  end

  def show_edit?
    params[:controller] == 'neighborhoods'
  end
end

app/views/neighborhoods/_form.html.erb
  <div class="span8 offset4">
  <%= form_for @neighborhood, :html => { :multipart => true }, :validate => true do |f| %>
    <% if @neighborhood.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @neighborhood.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %> 
  
    <%= f.hidden_field :city_id, value: @city.id %> 
    <div><%= f.text_field :name, placeholder: "Neighborhood Name", autofocus: true  %></div>
    <div><%= text_field_tag "zipcode", nil, disabled: true, placeholder: "Zipcode" %></div>
    <br />
    <div>Choose Cover Photo: <%= file_field_tag 'image' %></div>
    <br />
    <div><%= f.text_area :description, placeholder: "Describe the neighborhood.", :rows => 5 %></div>
    <div class="neighborhood-signup-btn btn">
      <div class="inner-margin2">
      <%= f.submit (current_user.neighborhoods.count == 0 ? 'Complete Sign Up!' : 'Save Neighborhood') %>
      </div>
    </div>
  <% end %>
  </div>

app/views/neighborhoods/_header.html.erb
<div class="inner bottom-border">
  <div class="container">
    <div class="row">
      <div class="span8">
        <ul class="nav nav-tabs">
          <li class= <%= 'active' if tab_active?(:neighborhoods) %>>
            <%= link_to @neighborhood.name, @neighborhood %>
          </li>
          <li><a href="javascript:void(0)">People</a></li>
          <li class= <%= 'active' if tab_active?(:places) %>>
            <%= link_to "Places", neighborhood_places_path(@neighborhood) %>
          </li>
          <li><a href="javascript:void(0)">Gallery</a></li>
          <li><a href="javascript:void(0)">Events</a></li>
        </ul>
      </div>
      <div class="main-actions span4">
        <% if current_user.neighborhoods.include?(@neighborhood) %>
          <% unless is_primary?(@neighborhood) %>
            <%= link_to "Leave", leave_neighborhood_path(@neighborhood), method: :post %>
            <%= link_to "Make Primary", primary_neighborhood_path(@neighborhood), method: :post %>
          <% end %>
        <% else %>
          <%= link_to "Join", join_neighborhood_path(@neighborhood) %>
        <% end %>
        <!--<%= link_to("Favorite", "/neighborhoods/#{@neighborhood.id}/add_to_favorites", method: :post) unless already_favorited?(@neighborhood) %>-->
        <% if show_edit? %>
          <%= link_to 'Edit', edit_neighborhood_path(@neighborhood) if is_owner?(@neighborhood) %>
        <% end %>
        <a href="#"><i class="icon-search single"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/neighborhoods/_neighborhood.html.erb
<div class="neighborhood-thumbnail span4">
  <div class="inner-margin2">
    <a href="<%= "#{neighborhood.id}/preview" %>" data-remote="true">
      <div class="neighborhood-thumbnail-img"></div>
      <%= image_tag neighborhood.photos.first.image.url(:medium) unless neighborhood.photos.empty? %>
      <div class="info">
        <span class="title"><%= neighborhood.name %></span>
        <p><i class="icon-user icon-white icon-large"></i> <%= neighborhood.users.count %> members</p>
      </div>
    </a>
  </div>
</div>

app/views/neighborhoods/_neighborhood_summary.html.erb
    <div id="neighborhood-summary-top">
<!--Task 773 should replace this map on the following line-->
        <div class="map">
            <iframe width="100%" height="177" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=23.221155,77.412415&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=23.232513,77.406921&amp;spn=0.104109,0.260239&amp;z=11&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?q=23.221155,77.412415&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=23.232513,77.406921&amp;spn=0.104109,0.260239&amp;z=11&amp;source=embed" style="color:#0000FF;text-align:left"></a></small>
        </div>
        <p><%= @neighborhood.description %></p>
        <div class="clear"></div>
    </div>
<h5><i class="icon-user"></i> People</h5>
<% for user in @neighborhood.users %>
    <%= image_tag user.profile_picture, class: "med-thumbnail" %>
<% end %>
<h5><i class="icon-map-marker"></i> Places</h5>
  <% for place in @neighborhood.places %>
    <div class="place-teaser">
        <%= image_tag(place.photos.first.image.url(:small), class: "mini-thumbnail") unless place.photos.empty? %>
        <div class="place-teaser-details">
          <span class="pt-title"><%= place.name %></span><br />
          <span class="stats"><i class='icon-comment'></i> <%= place.posts.count %> Reviews</span>
          <span class="stats"><i class='icon-heart'></i> <%= place.favorites.count %> Favorites</span>
        </div>
      </div>
  <% end %>

app/views/neighborhoods/_preview.html.erb
  <%= render @neighborhood %>
  
<div id="arrow-left">
  <div id="arrow-container">
    <div class="arrow-left backdrop"></div>
    <div class="arrow-left inner-white"></div>
    <div class="arrow-left inner-color"></div>
  </div>
</div>
<div class="neighborhood-summary span8">
  <div class="inner-margin2">
    <div class="inner-padding10">
      <%= render "neighborhood_summary", :neighborhood => @neighborhood %>
    </div>
  </div>
</div>

<div class="neighborhood-signup-btn btn">
  <div class="inner-margin2">
    <%= 
      link_to (current_user.neighborhoods.count == 0 ? 'Complete Sign Up!' : 'Save Neighborhood'),
      "/users/#{current_user.id}/add_neighborhood/#{@neighborhood.id}", 
      method: :post
    %>
  </div>
</div>

app/views/neighborhoods/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9">
          <%= form_for @neighborhood, html: { multipart: true}, validate: true do |f| %>
            <% if @neighborhood.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@neighborhood.errors.count, 'error') %> prohibited this post from being saved:</h2>
                <ul>
                  <% @neighborhood.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %> 
      
            <div>
              <%= f.text_field :name, placeholder: "Neighborhood Name", autofocus: true  %>
            </div>
            <div>
              <%= text_field_tag "zipcode", nil, disabled: true, placeholder: "Zipcode" %>
            </div>
            <br />
            <div>Choose Cover Photo: <%= file_field_tag 'image' %></div>
            <br />
            <div>
              <%= f.text_area :description, placeholder: "Describe the neighborhood.", rows: 5 %>
            </div>
            <div>
              <%= f.submit class: :btn %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/neighborhoods/find.html.erb
<section id="top-main">
  <div class="container">
    <div class="row">
      <div id="welcome" class="span12">
        <div class="row">
          <div id="welcome-left" class="span5">
            <div class="inner-padding">
              <% if current_user.neighborhoods.count == 0 %>
                <h1><%= "Welcome, #{@user.first_name}!" %></h1>
                <p>
                  In order for use to best serve you we need to know which neighborhood 
                  you live in. This will be your primary neighborhood. Don't worry, you
                  can change this later if needed.
                </p>
              <% else %>
                <h1>Add a new neighborhood!</h1>
                <p>Add another neighborhood!</p>
              <% end %>
            </div>
          </div>
          <div id="welcome-right" class="span7">
            <div class="inner-padding">
              <div>
                <%= select_tag(:state_id, options_from_collection_for_select(@states, :id, :name), prompt: "Select a State") %>
              </div> 
              <div>
                <%= grouped_collection_select(:neighborhood, :city_id, @states, :cities, :name, :id, :name) %> 
              </div>
            </div>
          </div>
        </div>
      </div> 
    </div>
        <div class="container no-padding">
            <div class="arrow-down"></div>
        </div>
        <div id="neidhborhood-btns">
            <div id="neighborhood-search" class="filter-btn triangle-isosceles right">
                <div class="inner-padding10">
                    <%= text_field_tag('search', nil, :disabled => true, :placeholder => "Search Neighborhoods") %>
                </div>
            </div>
            <div id="neighborhood-create" class="filter-btn triangle-isosceles left">
                <div class="inner-padding10">
                    <%= link_to "Create Neighborhood", new_neighborhood_path, :class => "new_neighborhood_link", remote: true %>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="bottom-main">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div id="neighborhoods" class="row"></div>
      </div>
    </div>
  </div>
</section>

app/views/neighborhoods/index.html.erb
<%= render @neighborhoods %>

app/views/neighborhoods/new.html.erb
This is the new neighborhood view.

app/views/neighborhoods/new.js.erb
$('#neighborhoods').empty().html('<%= j render "form" %>');
$('#new_neighborhood').enableClientSideValidations();

app/views/neighborhoods/preview.js.erb
$('#neighborhoods').empty().html('<%= j render "preview" %>')

app/views/neighborhoods/select_photos.html.erb
<%= render "header" %>

<%= render "photos/form" %>

app/views/neighborhoods/show.html.erb
<%= render "header" %>
<div class="container">
  <div class="row">
    <div class="span12">
      <section id="neighborhood-members">
        <% @neighborhood.users.each do |user| %>
            <%= link_to(image_tag(user.profile_picture(:small), class: "med-thumbnail"), user) %>
        <% end %>
        <a href="javascript:void(0)" class="more"><i class="icon-arrow-right"></i>More</a>
      </section>
      <div class="row padding-top">
        <section id="neighborhood-feed" class="span7">
          <%= render "posts/form" %>
          <%= render @posts %>
        </section>
        <section id="neighborhood-sidebar" class="span5">
          
          <div id="neighborhood-photos" class="block">
            <div class="hit-area"><a href="<%= "/neighborhoods/#{@neighborhood.id}/select_photos" %>" class="add-photos-btn"><i class="icon-plus"></i>Add Photos</a></div>
            <%= image_tag @neighborhood.photos.last.image.url(:medium), class: "neighborhood-main-photo" unless @neighborhood.photos.empty? %>
            <div class="neighborhood-photo-thumbnails">
            <% @neighborhood.photos.each do |photo| %>
              <%= image_tag photo.image.url(:medium), class: "neighborhood-photo-thumb" %>
            <% end %>
            <a href="javascript:void(0)" class="more"><i class="icon-arrow-right"></i></a>
            </div>
          </div>
            
          <h2>Neighborhood Details</h2>
          <div id="neighborhood-details" class="block">
            <p><%= @neighborhood.description %></p>
<!--Task 773 should replace this map on the following line-->
            <iframe width="100%" height="165" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=23.221155,77.412415&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=23.232513,77.406921&amp;spn=0.104109,0.260239&amp;z=11&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?q=23.221155,77.412415&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=23.232513,77.406921&amp;spn=0.104109,0.260239&amp;z=11&amp;source=embed" style="color:#0000FF;text-align:left"></a></small>
          </div>
          
          <h2>Places<a href="<%= new_neighborhood_place_path(@neighborhood) %>" class="add-btn"><i class="icon-plus"></i>Create a Place</a></h2>
          
          <div id="neighborhood-places" class="block">
            
            <% @places.each do |place| %>
              <div class="place-teaser">
                <%= link_to neighborhood_place_path(@neighborhood, place) do %>
                  <%= (image_tag place.photos.last.image.url(:medium)) unless place.photos.empty? %>
                  <div class="place-teaser-details">
                    <span class="pt-title"><%= place.name %></span>
                    <br>
                    <span class="stats"><i class="icon-comment"></i> 0 Reviews</span>
                    <span class="stats"><i class="icon-heart"></i> <%= pluralize(place.favorites.count, "Favorite") %></span>
                  </div>
                <% end %>
              </div>
            <% end %>
            
            <a class="white-btn" href="<%= neighborhood_places_path(@neighborhood) %>"><i class="icon-arrow-right"></i>View More Places</a>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>