config/routes.rb
Neighborhoods::Application.routes.draw do
 
  resources :places
  resources :photos
  resources :posts
  resources :places
  resources :friendships, only: [:create, :destroy]

  devise_for :users

  root :to => redirect('/users/sign_up')

  authenticated :user do
    root to: "users#main_feed"
  end
 
  match "users/:id/add_neighborhood/:neighborhood_id" => "users#add_neighborhood", :via => :post 
  match "users/:id/main_feed"                         => "users#main_feed"
  
  resources :users do
    resources :posts
    resources :friendships, only: [:index]
  end

  match "neighborhoods/find"                                => "neighborhoods#find"
  match "neighborhoods/:id/preview"                         => "neighborhoods#preview"
  match "neighborhoods/:id/join"                            => "neighborhoods#join",          as: :join_neighborhood
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave",         as: :leave_neighborhood, via: :post
  match "neighborhoods/:id/primary"                         => "neighborhoods#primary",       as: :primary_neighborhood, via: :post
  match "neighborhoods/:id/leave"                           => "neighborhoods#leave"
  match "neighborhoods/:id/select_photos"                   => "neighborhoods#select_photos"
  match "neighborhoods/:id/add_photos"                      => "neighborhoods#add_photos",    :via => :post
  match "neighborhoods/:id/add_to_favorites"                => "favorites#add_to_favorites",  :via => :post
  
  resources :neighborhoods do
    resources :posts
    resources :places do
      resources :posts
    end
  end
  
  match "neighborhoods/:neighborhood_id/places/:id/add_to_favorites" => "favorites#add_to_favorites", :via => :post
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :state_id

  has_many :neighborhoods
  belongs_to :state
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :neighborhood_id, :place_id, :user_id
  
  belongs_to :user
  belongs_to :neighborhood
  belongs_to :place
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user_id, :friend_id 

  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_uniqueness_of :friend_id, scope: :user_id  
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  attr_accessible :name, :city_id, :description
  
  has_many :neighborhood_users
  has_many :users, through: :neighborhood_users

  belongs_to :city
  has_many :posts, dependent: :destroy
  has_many :photos
  has_many :places
  has_many :favorites, dependent: :destroy
  has_many :ownerships, dependent: :destroy
  has_many :owners, through: :ownerships
  
  validates_presence_of   :name
  validates_uniqueness_of :name, :scope => :city_id
end

app/models/neighborhood_user.rb
class NeighborhoodUser < ActiveRecord::Base
  attr_accessible :primary, :user_id, :neighborhood_id

  belongs_to :user
  belongs_to :neighborhood
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  attr_accessible :neighborhood_id, :place_id, :user_id

  belongs_to :user
  belongs_to :neighborhood
  belongs_to :place
  belongs_to :owner, class_name: "User", foreign_key: :user_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image, :user_id, :neighborhood_id, :place_id
  
  include Shared::PaperclipHelper
  has_attachment :image, :styles => { :small   => "100x100>",
                                         :medium  => "300x300>" }
 
  belongs_to :user
  belongs_to :neighborhood 
  belongs_to :place
  
  validates_presence_of :user_id

  default_scope lambda { order('id ASC') }
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :category, :name, :street_address, :zipcode, :website, :phone, :description, :neighborhood_id, :user_id

  belongs_to :neighborhood
  belongs_to :user
  has_many :photos
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :ownerships, dependent: :destroy
  has_many :owners, through: :ownerships
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id, :neighborhood_id, :place_id

  belongs_to :user
  belongs_to :neighborhood
  belongs_to :place

  validates_presence_of :user_id, :content
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :gender, :birthday, :about

  validates_presence_of :first_name, :last_name, :gender, :birthday

  has_many :neighborhood_users
  has_many :neighborhoods, through: :neighborhood_users

  has_many :posts, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :places
  has_many :favorites, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :ownerships, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end

  def profile_picture(size = :small)
    if self.profile_picture_id != nil 
      photo = Photo.find(self.profile_picture_id)
      photo.image.url(size)
    else
      "missing_profile_picture.png"
    end
  end

  def primary_neighborhood
    neighborhood_users.where(primary: true).first.neighborhood
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def already_favorited?(object)
    type = object.class
    if type == Neighborhood
      return Favorite.where("user_id = ? AND neighborhood_id = ?", current_user.id, object.id).exists?
    else
      return Favorite.where("user_id = ? AND place_id = ?", current_user.id, object.id).exists?
    end
  end

  def tab_active?(action)
    params[:controller] == action.to_s
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

  def already_friends?(user)
    current_user.friends.include?(user) 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper

  def is_owner?(object)
    object.owners.include?(current_user)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  def category_list
    [
      'Restaurants & Cafes',
      'Bars',
      'Pubs & Clubs',
      'Shopping',
      'Art',
      'Theater'
    ]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_edit_path(post)
    puts "+++++++++++++++++++++++++++++++"
    if defined?(@place) and defined?(@neighborhood)
      edit_neighborhood_place_post_path(@neighborhood, @place, post)
    elsif defined?(@neighborhood)
      edit_neighborhood_post_path(@neighborhood, post)
    else
      edit_post_path(post)
    end
  end

  def get_delete_path(post)
    if defined?(@place) and defined?(@neighborhood)
      neighborhood_place_post_path(@neighborhood, @place, post)
    elsif defined?(@neighborhood)
      neighborhood_post_path(@neighborhood, post)
    else
      post_path(post)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_nav_link(user, user_id)
    current_user = find_user(user, user_id)
    link_to current_user.full_name, current_user, class: 'profile-name'
  end

  def find_user(user, user_id)
    if user_id.present?
      user.id == user_id ? user : User.find(user_id)
    else
      user
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighborhoods</title>
  <link href='http://fonts.googleapis.com/css?family=Raleway:200|Open+Sans+Condensed:700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="<% if user_signed_in? %>small<% end %>">
    <div class="container">
      <div class="row">
        <div id="logo" class="span3">
          <%= link_to image_tag("placeholder-logo.png", border: 0), root_path %>
        </div>
        <nav class="span9">
          <div class="navbar">
            <ul class="nav pull-right">
            <% if user_signed_in? %>
              <% unless current_user.neighborhoods.empty? %>
                <li><a href="/"><i class="icon-home"></i></a></li>
                <li><a href="#"><i class="icon-bullhorn"></i></a></li>
                <li class="dropdown logged">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= image_tag(current_user.profile_picture(:small), class: "mini-thumbnail") %> <%= current_user.full_name %></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><a href="<%= user_path(current_user) %>"><i class="icon-user"></i> <%= current_user.full_name %></a></li>
                    <li><a href="<%= edit_user_path(current_user) %>"><i class="icon-pencil"></i> Edit Profile</a></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="icon-signout"></i> 
                        Logout
                      <% end %>
                    </li>
                    <hr style="margin:5px 0;">
                    <% current_user.neighborhoods.each do |nh| %>
                      <li><a href="<%= neighborhood_path(nh) %>"><i class="icon-arrow-right"></i> <%= nh.name %></a></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            <% else %>
              <li class="dropdown home">
                <a id="login" class="dropdown-toggle" data-toggle="dropdown" href="#">Log in</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <div class="inner-padding10">
                    <%= render "devise/sessions/new" %>
                  </div>
                </ul>
              </li>
            <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <section id="main-content">
    <div class="container no-padding">
    <% if flash[:error] %>
      <p class='alert alert-error'><%=h flash[:error] %><a class="close" data-dismiss="alert" href="#">&times;</a></p>
    <% end -%>
    <% if flash[:notice] %>
      <p class='alert alert-info'><%=h flash[:notice] %><a class="close" data-dismiss="alert" href="#">&times;</a></p>
    <% end -%>
    <% if flash[:success] %>
      <p class='alert alert-success'><%=h flash[:success] %><a class="close" data-dismiss="alert" href="#">&times;</a></p>
    <% end -%>
    </div>
    <%= yield %>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="span12">Forbes Footer Info</div>
      </div>
    </div>
  </footer>
</body>
</html>